// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackMuvi.Data;

#nullable disable

namespace TrackMuvi.Data.Migrations
{
    [DbContext(typeof(TrackMuviDbContext))]
    [Migration("20260801183251_AddTitleCache")]
    partial class AddTitleCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TrackMuvi.Data.Entities.EpisodeWatchEntity", b =>
                {
                    b.Property<string>("TitleKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TitleKey", "SeasonNumber", "EpisodeNumber");

                    b.ToTable("EpisodeWatches");
                });

            modelBuilder.Entity("TrackMuvi.Data.Entities.PersonalStatusEntity", b =>
                {
                    b.Property<string>("TitleKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Abandoned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Following")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Want")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Watched")
                        .HasColumnType("INTEGER");

                    b.HasKey("TitleKey");

                    b.ToTable("PersonalStatuses");
                });

            modelBuilder.Entity("TrackMuvi.Data.Entities.TitleCacheEntity", b =>
                {
                    b.Property<string>("TitleKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NextEpisodeAirDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextEpisodeName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextEpisodeSeason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("TitleKey");

                    b.ToTable("TitleCache");
                });

            modelBuilder.Entity("TrackMuvi.Data.Entities.ViewHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TitleKey");

                    b.ToTable("ViewHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
