// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackMuvi.Data;

#nullable disable

namespace TrackMuvi.Data.Migrations
{
    [DbContext(typeof(TrackMuviDbContext))]
    partial class TrackMuviDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TrackMuvi.Data.Entities.PersonalStatusEntity", b =>
                {
                    b.Property<string>("TitleKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Abandoned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Following")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Want")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Watched")
                        .HasColumnType("INTEGER");

                    b.HasKey("TitleKey");

                    b.ToTable("PersonalStatuses");
                });

            modelBuilder.Entity("TrackMuvi.Data.Entities.ViewHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TitleKey");

                    b.ToTable("ViewHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
